[tool.poetry]
name = "videomaker-helper"
version = "0.1.0"
description = "Simples tools to help video makers"
authors = ["dunossauro <mendesxeduardo@gmail.com>"]
readme = "README.md"
packages = [{include = "vmh"}]
classifiers = [
    "Environment :: Console",
]

[tool.poetry.dependencies]
python = "^3.11"
pydub = "^0.25.1"
typer = "^0.9.0"
loguru = "^0.7.0"
tinydb = "^4.8.0"
rich = "^13.5.2"
pedalboard = "^0.7.7"
parsel = "^1.8.1"
moviepy = "v2.0.0.dev2"
appdirs = "^1.4.4"
whisper = "^1.1.10"
llvmlite = "^0.40.1"
numba = "^0.57.1"
openai-whisper = {git = "https://github.com/openai/whisper.git"}
torch = "^2.0.1+cpu"
torchvision = "^0.15.2+cpu"
torchaudio = "^2.0.2+cpu"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
blue = "^0.9.1"
ruff = "^0.0.282"

[tool.isort]
profile = "black"
line_length = 79

[tool.poetry.scripts]
vmh = "vmh.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"