name: Pipeline
on:
  push:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install poetry
        run: pipx install --python python3.11 poetry

      - name: Install dependencies
        run: poetry install

      - name: Check ruff
        run: poetry run ruff .

      - name: Mypy check
        run: poetry run mypy .
